[tool.black]
line-length = 79
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 79

[tool.pylint]
max-line-length = 79
disable = "too-few-public-methods"

[tool.mypy]
strict = true
exclude = "gunicorn"
ignore_missing_imports = true

[tool.coverage.run]
source = ["src/ofa"]
omit = ["tests/*"]

[tool.coverage.report]
fail_under = 80