name: 'Linting'
on:
  pull_request:
    branches:
      - "main"
permissions:
  pull-requests: write
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Update PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
      - name: Run Linter
        run: |
            python -m pylint --fail-under=9 --rcfile=pyproject.toml ./src > pylint_report.txt
            python -m pylint --fail-under=9 --rcfile=pyproject.toml ./tests >> pylint_report.txt
      - name: Generate linter report
        if: ${{ success() || failure() }}
        run: |
            echo -e "Linter Report:\n\`\`\`\n$(tail -1000 pylint_report.txt)\n\`\`\`" > pylint_report_final.txt
      - name: Log linter report
        if: ${{ success() || failure() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./pylint_report_final.txt
          comment_tag: pylint
          mode: recreate
