name: 'Tests'
on:
  pull_request:
    branches:
      - "main"
permissions:
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Update PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
      - name: Run Tests
        id: tests_and_coverage
        continue-on-error: true
        run: |
            python -m coverage run -m unittest discover -s tests -p "test_*.py"
            python -m coverage report --rcfile=pyproject.toml >> coverage_report.txt
      - name: Log coverage percentage
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./coverage_report.txt
          comment_tag: coverage

